import { APP_ROUTES } from '../../src/app/config/app.config';

export const A11Y_E2E = {
  TEST_TIMEOUT_MS: 60_000,
  MAIN_CONTENT_VISIBLE_TIMEOUT_MS: 30_000,
  PRIVACY_DIALOG_VISIBLE_TIMEOUT_MS: 5000,
  ROUTES: [
    APP_ROUTES.MAIN,
    APP_ROUTES.APPLICANTS,
    APP_ROUTES.MATCH,
    APP_ROUTES.EXPORT,
    APP_ROUTES.SMART_ACTION,
    APP_ROUTES.PRIVACY,
  ],
} as const;
