export enum ApplicantActionTypes {
  LoadApplicants = '[Applicants] Load Applicants',
  LoadApplicantsSuccess = '[Applicants] Load Applicants Success',
  LoadApplicantsFailure = '[Applicants] Load Applicants Failure',
  ApplicantsRosterLoaded = '[Applicants] Roster Loaded',
  AddApplicant = '[Applicants] Add Applicant',
  AddApplicantSuccess = '[Applicants] Add Applicant Success',
  AddApplicantFailure = '[Applicants] Add Applicant Failure',
  UpdateApplicant = '[Applicants] Update Applicant',
  UpdateApplicantSuccess = '[Applicants] Update Applicant Success',
  UpdateApplicantFailure = '[Applicants] Update Applicant Failure',
  DeleteApplicant = '[Applicants] Delete Applicant',
  DeleteApplicantSuccess = '[Applicants] Delete Applicant Success',
  DeleteApplicantFailure = '[Applicants] Delete Applicant Failure',
  SetGlobalFilter = '[Applicants] Set Global Filter',
  SetSortBy = '[Applicants] Set Sort By',
  SetViewType = '[Applicants] Set View Type',
  SetFilterBySkill = '[Applicants] Set Filter By Skill',
  SetFilterByStatus = '[Applicants] Set Filter By Status',
  SetFilterByCountry = '[Applicants] Set Filter By Country',
  SearchLocationSuggestions = '[Applicants] Search Location Suggestions',
  SearchLocationSuggestionsSuccess = '[Applicants] Search Location Suggestions Success',
  SearchLocationSuggestionsFailure = '[Applicants] Search Location Suggestions Failure',
  ClearLocationSuggestions = '[Applicants] Clear Location Suggestions',
  LoadApplicantDetailSuccess = '[Applicants] Load Applicant Detail Success',
}
