export enum ApplicantActionTypes {
  LoadApplicants = '[Applicants] Load Applicants',
  LoadApplicantsFailure = '[Applicants] Load Applicants Failure',
  RosterLoaded = '[Applicants] Roster Loaded',
  AddApplicant = '[Applicants] Add Applicant',
  AddApplicantSuccess = '[Applicants] Add Applicant Success',
  AddApplicantFailure = '[Applicants] Add Applicant Failure',
  UpdateApplicant = '[Applicants] Update Applicant',
  UpdateApplicantSuccess = '[Applicants] Update Applicant Success',
  UpdateApplicantFailure = '[Applicants] Update Applicant Failure',
  DeleteApplicant = '[Applicants] Delete Applicant',
  DeleteApplicantSuccess = '[Applicants] Delete Applicant Success',
  DeleteApplicantFailure = '[Applicants] Delete Applicant Failure',
  SyncFiltersFromUrl = '[Applicants] Sync Filters From URL',
  PatchFilters = '[Applicants] Patch Filters',
  SetSortBy = '[Applicants] Set Sort By',
  SetViewType = '[Applicants] Set View Type',
  OpenApplicantForm = '[Applicants] Open Applicant Form',
  OpenConfirmDeleteApplicant = '[Applicants] Open Confirm Delete Applicant',
  ApplicantFormDialogClosed = '[Applicants] Applicant Form Dialog Closed',
  SetNewApplicantFabExpanded = '[Applicants] Set New Applicant FAB Expanded',
  SearchLocationSuggestions = '[Applicants] Search Location Suggestions',
  SearchLocationSuggestionsSuccess = '[Applicants] Search Location Suggestions Success',
  SearchLocationSuggestionsFailure = '[Applicants] Search Location Suggestions Failure',
  ClearLocationSuggestions = '[Applicants] Clear Location Suggestions',
}
